#!/bin/sh
# Cleanup lighttpd compress cache
cd /
cache=/var/cache/lighttpd
if test -d "$cache/compress"; then
    runuser -u www-data -- /bin/sh -c "find $cache/compress -type f -atime +30 -print0 | xargs -0 -r rm"
fi
if test -d "$cache/uploads"; then
    runuser -u www-data -- /bin/sh -c "find $cache/uploads -type f -atime +1 -print0 | xargs -0 -r rm"
fi
